# sample configuration file for config entirely local, not using remote config service
# can be overridden by command-line arguments

# standard reference of type and version
version: config.databack.io/v1
kind: local

spec:

  # set logging level, one of: error,warning,info,debug,trace; default is info
  logging: info 

  # dump, or backup, configuration
  dump:
    include: # optional, otherwise will do all tables except system tables
      - table1
      - table2
    exclude: # optional, otherwise will do all tables except system tables
      - table3
      - table4
    safechars: true # defaults to false
    noDatabaseName: false # remove the `USE <database>` statement from backup files, defaults to false
    # schedule to dump, can use one of: cron, frequency, once. If frequency is set, begin will be checked
    schedule:
      once: true # run only once and exit; ignores all other scheduling. Defaults to false
      cron: "0 10 * * *"
      frequency: 1440 # in minutes
      begin: +25 # What time to do the first dump. Must be in one of two formats: Absolute: HHMM, e.g. `2330` or `0415`; or Relative: +MM, i.e. how many minutes after starting the container, e.g. `+0` (immediate), `+10` (in 10 minutes), or `+90` in an hour and a half"
    compression: gzip # defaults to gzip
    compact: true # defaults to false
    maxAllowedPacket: 4194304 # defaults to 4194304
    filenamePattern: db_backup_{{ .now }}.{{ .compression }}
    scripts:
      preBackup: /path/to/prescripts/
      postBackup: /path/to/postscripts/
    # list of named targets to backup to, from the index below
    targets:
      - s3
      - file
      - otherfile
      - smbshare

  restore:
    scripts:
      preRestore: /path/to/prescripts/
      postRestore: /path/to/postscripts/

  # database configuration
  database:
    server: host
    port: port
    credentials:
      username: user
      password: password

  # targets. Each target is a location, as well as credentials and config, as needed
  targets:
    s3:
      type: s3
      url: s3://bucket.us-west.amazonaws.com/databackup
      details:
        region: us-west-1
        endpoint: https://s3.us-west-1.amazonaws.com
        accessKeyId: access_key_id
        secretAccessKey: secret_access_key
    file:
      type: file
      url: file:///tmp/databackup
    otherfile:
      type: file
      url: /tmp/databackup
    smbshare:
      type: smb
      url: smb://cifshost:2125/databackup
      details:
        domain: mydomain
        username: user
        password: password
